[workspace]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64"] 

[dependencies]
python = "=3.10.13"
numpy = "=1.26.4"
netCDF4 = "=1.6.4"
zarr = "=2.18.3"
xarray = "=2025.6.1"
pyinterp = "=2025.8.1"
pcraster = ">=4.4.2,<5"
rsync = ">=3.4.2,<4"
rich = ">=15.0.0,<16"

[pypi-dependencies]
pcrglobwb = { path = ".", editable = true }

[feature.lint.dependencies]
pre-commit = "=4.6.2"

[feature.dev.dependencies]
act = "=0.2.89"
vulture = "=2.16"

[environments]
default = { features = [], solve-group = "default" }
lint = { features = ["lint"], no-default-feature = true }
dev = { features = ["dev", "lint"], solve-group = "default" }
