qsub -v CLONE_CODE=1  -N CLONE_CODE=test-1  pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE=2  -N CLONE_CODE=test-2  pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE=3  -N CLONE_CODE=test-3  pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE=4  -N CLONE_CODE=test-4  pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE=5  -N CLONE_CODE=test-5  pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE=6  -N CLONE_CODE=test-6  pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE=7  -N CLONE_CODE=test-7  pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE=8  -N CLONE_CODE=test-8  pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE=9  -N CLONE_CODE=test-9  pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE=10 -N CLONE_CODE=test-10 pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE=11 -N CLONE_CODE=test-11 pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE=12 -N CLONE_CODE=test-12 pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE=13 -N CLONE_CODE=test-13 pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE=14 -N CLONE_CODE=test-14 pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE=15 -N CLONE_CODE=test-15 pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE=16 -N CLONE_CODE=test-16 pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE=17 -N CLONE_CODE=test-17 pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE=18 -N CLONE_CODE=test-18 pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE=19 -N CLONE_CODE=test-19 pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE=20 -N CLONE_CODE=test-20 pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE=21 -N CLONE_CODE=test-21 pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE=22 -N CLONE_CODE=test-22 pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE=23 -N CLONE_CODE=test-23 pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE=24 -N CLONE_CODE=test-24 pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE=25 -N CLONE_CODE=test-25 pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE=26 -N CLONE_CODE=test-26 pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE=27 -N CLONE_CODE=test-27 pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE=28 -N CLONE_CODE=test-28 pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE=29 -N CLONE_CODE=test-29 pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE=30 -N CLONE_CODE=test-30 pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE=31 -N CLONE_CODE=test-31 pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE=32 -N CLONE_CODE=test-32 pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE=33 -N CLONE_CODE=test-33 pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE=34 -N CLONE_CODE=test-34 pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE=35 -N CLONE_CODE=test-35 pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE=36 -N CLONE_CODE=test-36 pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE=37 -N CLONE_CODE=test-37 pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE=38 -N CLONE_CODE=test-38 pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE=39 -N CLONE_CODE=test-39 pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE=40 -N CLONE_CODE=test-40 pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE=41 -N CLONE_CODE=test-41 pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE=42 -N CLONE_CODE=test-42 pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE=43 -N CLONE_CODE=test-43 pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE=44 -N CLONE_CODE=test-44 pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE=45 -N CLONE_CODE=test-45 pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE=46 -N CLONE_CODE=test-46 pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE=47 -N CLONE_CODE=test-47 pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE=48 -N CLONE_CODE=test-48 pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE=49 -N CLONE_CODE=test-49 pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE=50 -N CLONE_CODE=test-50 pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE=51 -N CLONE_CODE=test-51 pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE=52 -N CLONE_CODE=test-52 pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE=53 -N CLONE_CODE=test-53 pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE=54 -N CLONE_CODE=test-54 pbs_template_serial_per_clone.sh
