qsub  -v CLONE_CODE_ONE=1,CLONE_CODE_TWO=11 -N test-01,11 pbs_template_serial_per_clone.sh
qsub  -v CLONE_CODE_ONE=2,CLONE_CODE_TWO=12 -N test-02,12 pbs_template_serial_per_clone.sh
qsub  -v CLONE_CODE_ONE=3,CLONE_CODE_TWO=13 -N test-03,13 pbs_template_serial_per_clone.sh
qsub  -v CLONE_CODE_ONE=4,CLONE_CODE_TWO=14 -N test-04,14 pbs_template_serial_per_clone.sh
qsub  -v CLONE_CODE_ONE=5,CLONE_CODE_TWO=15 -N test-05,15 pbs_template_serial_per_clone.sh
qsub  -v CLONE_CODE_ONE=6,CLONE_CODE_TWO=16 -N test-06,16 pbs_template_serial_per_clone.sh
qsub  -v CLONE_CODE_ONE=7,CLONE_CODE_TWO=17 -N test-07,17 pbs_template_serial_per_clone.sh
qsub  -v CLONE_CODE_ONE=8,CLONE_CODE_TWO=18 -N test-08,18 pbs_template_serial_per_clone.sh
qsub  -v CLONE_CODE_ONE=9,CLONE_CODE_TWO=19 -N test-09,19 pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE_ONE=10,CLONE_CODE_TWO=20 -N test-10,20 pbs_template_serial_per_clone.sh

qsub -v CLONE_CODE_ONE=21,CLONE_CODE_TWO=31 -N test-21,31 pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE_ONE=22,CLONE_CODE_TWO=32 -N test-22,32 pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE_ONE=23,CLONE_CODE_TWO=33 -N test-23,33 pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE_ONE=24,CLONE_CODE_TWO=34 -N test-24,34 pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE_ONE=25,CLONE_CODE_TWO=35 -N test-25,35 pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE_ONE=26,CLONE_CODE_TWO=36 -N test-26,36 pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE_ONE=27,CLONE_CODE_TWO=37 -N test-27,37 pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE_ONE=28,CLONE_CODE_TWO=38 -N test-28,38 pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE_ONE=29,CLONE_CODE_TWO=39 -N test-29,39 pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE_ONE=30,CLONE_CODE_TWO=40 -N test-30,40 pbs_template_serial_per_clone.sh

qsub -v CLONE_CODE_ONE=41,CLONE_CODE_TWO=48 -N test-41,48 pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE_ONE=42,CLONE_CODE_TWO=49 -N test-42,49 pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE_ONE=43,CLONE_CODE_TWO=50 -N test-43,50 pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE_ONE=44,CLONE_CODE_TWO=51 -N test-44,51 pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE_ONE=45,CLONE_CODE_TWO=52 -N test-45,52 pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE_ONE=46,CLONE_CODE_TWO=53 -N test-46,53 pbs_template_serial_per_clone.sh
qsub -v CLONE_CODE_ONE=47,CLONE_CODE_TWO=54 -N test-47,54 pbs_template_serial_per_clone.sh
