name: Format and Lint

on: [push, pull_request]

permissions:
  contents: read

jobs:
  format-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.13

      - name: Install pre-commit
        run: pip install pre-commit
      
      - name: Run pre-commit
        run: |
          pre-commit run --hook-stage manual autoflake-check
          pre-commit run --hook-stage manual isort-check
          pre-commit run --hook-stage manual black-check
          pre-commit run --hook-stage manual flake8
